/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 * Author:  Edoardo
 * Created: 9-mag-2017
 */

/*  DATI ACCESSO DATABASE
    username= utente
    password = password
*/

CREATE TABLE utente(
    nome VARCHAR(32),
    cognome VARCHAR(32),
    urlFotoProfilo VARCHAR(1024),
    frasePres VARCHAR(256),
    dataNasc VARCHAR(256),
    username VARCHAR(256) NOT NULL,
    password VARCHAR(256) NOT NULL,
    idUtente INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
);

CREATE TABLE gruppo(
    urlFotoGruppo VARCHAR(1024),
    interesse VARCHAR(1024),
    nome VARCHAR(1024),
    idGruppo INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    idAmministratore INTEGER,
    FOREIGN KEY (idAmministratore) REFERENCES utente(idUtente)

);

CREATE TABLE PostType(
    idType INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(32)
);

CREATE TABLE post(
    idPostType INTEGER,
    FOREIGN KEY (idPostType) REFERENCES PostType(idType),
    content VARCHAR(1024),
    text VARCHAR(1024),
    idPost INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    idMittente INTEGER,
    FOREIGN KEY(idMittente) REFERENCES utente(idUtente),
    idDestinatarioUtente INTEGER,
    FOREIGN KEY(idDestinatarioUtente) REFERENCES utente(idUtente),
    idDestinatarioGruppo INTEGER,
    FOREIGN KEY(idDestinatarioGruppo) REFERENCES gruppo(idGruppo)  
);

CREATE TABLE amicizia(
    follower INTEGER,
    FOREIGN KEY(follower) REFERENCES utente(idUtente),
    followed INTEGER,
    FOREIGN KEY(followed) REFERENCES utente(idUtente),
    PRIMARY KEY (follower,followed)
);

CREATE TABLE partecipazioneGruppo(
    idUtente INTEGER,
    idGruppo INTEGER,
    FOREIGN KEY(idUtente) REFERENCES utente(idUtente),
    FOREIGN KEY(idGruppo) REFERENCES gruppo(idGruppo)
);

--Inserimento Utenti
INSERT INTO utente(nome,cognome,urlFotoProfilo,frasePres,dataNasc,username,password,idUtente)
VALUES('Edoardo','Demuru','img/utente1.jpg','Ciò che non ti uccide ti rende più forte','1995-06-18',
       'edo95','abcd',default);

INSERT INTO utente(nome,cognome,urlFotoProfilo,frasePres,dataNasc,username,password,idUtente)
VALUES('Marco','Broccolo','img/utente2.jpg','Che la forza sia con te','1998-09-20',
       'marco23','456',default);

INSERT INTO utente(nome,cognome,urlFotoProfilo,frasePres,dataNasc,username,password,idUtente)
VALUES('Giovanni','','img/utente3.jpg','','1994-02-27',
       'ciao94','4325',default);

--Inserimento gruppi
INSERT INTO gruppo(urlFotoGruppo,interesse,nome,idGruppo,idAmministratore)
VALUES('img/gruppo2.jpg','Studio','Ingegneria',default,2);

INSERT INTO gruppo(urlFotoGruppo,interesse,nome,idGruppo,idAmministratore)
VALUES('img/gruppo1.jpg','Studio','Informatica',default,1);

--Tipi di Post
INSERT INTO PostType(idType,name)
VALUES(0,'TEXT');

INSERT INTO PostType(idType,name)
VALUES(1,'IMAGE');

INSERT INTO PostType(idType,name)
VALUES(2,'LINK'); 

--Inserimento Post
INSERT INTO post(idPostType,content,text,idPost,idMittente,idDestinatarioUtente,idDestinatarioGruppo)
VALUES(0,'','Ehi ciao! Da quanto non ci sentiamo! Vediamoci appena puoi!',default,2,1,null);

INSERT INTO post(idPostType,content,text,idPost,idMittente,idDestinatarioUtente,idDestinatarioGruppo)
VALUES(1,'img/djanni1.jpg','Ehi guarda la foto di questo bellissimo gatto!',default,2,1,null);

INSERT INTO post(idPostType,content,text,idPost,idMittente,idDestinatarioUtente,idDestinatarioGruppo)
VALUES(2,'https://www.youtube.com/watch?v=-OnRxfhbHB4',
'Ehi guarda questo video di youtube!',default,3,1,null);

--Amicizie
INSERT INTO amicizia(follower,followed)
VALUES(1,3),(2,1),(2,3); 

--Partecipazione ad un gruppo
INSERT INTO partecipazioneGruppo(idUtente,idGruppo)
VALUES(1,2),(1,3)







    


